name: bakugan_companion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_3d_controller: ^2.3.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: title_font
      fonts:
        - asset: assets/font/titles_font.otf
          weight: 700
    - family: body_font
      fonts:
        - asset: assets/font/body_font.ttf
          weight: 700
    - family: button_font
      fonts:
        - asset: assets/font/button_font.ttf

  assets:
    - assets/video/bakugan_opening.mp4
    - assets/images/Menu.png
    - assets/images/menu-2.png
    - assets/images/selection-bg.png
    - assets/images/match-bg.png
    - assets/images/logo.png
    - assets/images/cards/anverse.png
    - assets/images/cards/cards.json
    - assets/images/cards/base/
    - assets/images/cards/new_vestroia/
    - assets/music/menu/Title.flac
    - assets/music/menu/Menu.flac
    - assets/music/arena/
    - assets/music/battle/before_ability.flac
    - assets/music/battle/after_ability.flac
    - assets/sound/
    - assets/images/characters/dan.png
    - assets/images/characters/runo.png
    - assets/images/characters/shun.png
    - assets/images/characters/alice.png
    - assets/images/characters/julie.png
    - assets/images/characters/marucho.png
    - assets/images/characters/masquerade.png
    - assets/images/attributes/pyrus_game.png
    - assets/images/attributes/aquos_game.png
    - assets/images/attributes/subterra_game.png
    - assets/images/attributes/haos_game.png
    - assets/images/attributes/darkus_game.png
    - assets/images/attributes/ventus_game.png
    # Carpetas de modelos
    - assets/models/dragonoid/
    - assets/models/gorem/
    - assets/models/fear_ripper/
    - assets/models/griffon/
    - assets/models/sirenoid/
    - assets/models/ravenoid/
    - assets/models/centipoid/
    - assets/models/reaper/
    - assets/models/monarus/
    - assets/models/harpus/
    - assets/models/blade_tigrerra/
    - assets/models/hammer_gorem/
    - assets/models/fourtress/
    - assets/models/preyas_diablo/
    - assets/models/rattleoid/
    - assets/models/stinglash/
    - assets/models/tentaclear/
    - assets/models/juggernoid/
    - assets/models/neo_dragonoid/
    - assets/models/bee_striker/
    - assets/models/cosmic_ingram/
    - assets/models/nemus/
    - assets/models/wired/
    - assets/models/apollonir/
    - assets/models/clayf/
    - assets/models/el_condor/
    - assets/models/fencer/
    - assets/models/lars_lion/
    - assets/models/leefram/
    - assets/models/limulus/
    - assets/models/naga/
    - assets/models/oberus/
    - assets/models/spin_ravenoid/
    - assets/models/warius/
